version: "3.1"

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb_arkanoid
    restart: always
    networks:
      - bridge
    volumes:
      - ./containers/influxdb_arkanoid_storage:/var/lib/influxdb
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=arkanoid
      - INFLUXDB_USER=arkanoid_publisher
      - INFLUXDB_USER_PASSWORD=1 
 
  mosquitto:
    image: eclipse-mosquitto:1.6.14
    container_name: arkanoid_broker
    restart: always
    networks:
      - bridge
    ports:
      - '1883:1883'
      - '9001:9001'

  telegraf:
    image: telegraf:latest
    container_name: telegraf_arkanoid
    networks:
      - bridge
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    ports:
      - '8094:8094'
      - '8092:8092'
      - '8125:8125'      

  
